#!/usr/bin/env python3
"""Browser checks for harcama-sifreli.html.

    pip install playwright && python3 tests/test_page.py

Serves the repository over http (localStorage needs a real origin), drives the
page with Chromium, and cross-checks its statement parser against the Python
CLI on the same file, so the two cannot drift apart silently.

The statement PDF is generated by make_fixture_pdf.py in the column layout the
real statements use — two right-aligned money columns, foreign-currency
originals, "n.Taksit" instalments, a "+" credit marker, undated fee rows and
the invisible 2pt spacer glyphs. No real statement is used or needed.
"""

import functools
import http.server
import json
import shutil
import socketserver
import subprocess
import sys
import tempfile
import threading
from pathlib import Path

from playwright.sync_api import sync_playwright

HERE = Path(__file__).resolve().parent
ROOT = HERE.parents[2]
CHROME = "/opt/pw-browsers/chromium-1194/chrome-linux/chrome"
PORT = 8731
TMP = Path(tempfile.mkdtemp())
PASSED = FAILED = 0


def check(label, got, want):
    global PASSED, FAILED
    if got == want:
        PASSED += 1
        print(f"  ok    {label}")
    else:
        FAILED += 1
        print(f"  FAIL  {label}\n          got  {got!r}\n          want {want!r}")


def make_budget(path, rows, months=("Ara", "Oca", "Sub")):
    import openpyxl
    workbook = openpyxl.Workbook()
    sheet = workbook.active
    sheet.title = "Butce"
    sheet["A1"] = "2026-2027 Kisisel Butce"
    sheet.append([])
    sheet.append(["Kategori", *months])
    for row in rows:
        sheet.append(row)
    workbook.save(path)


def serve():
    handler = functools.partial(http.server.SimpleHTTPRequestHandler, directory=str(ROOT))

    class Quiet(socketserver.TCPServer):
        allow_reuse_address = True

    server = Quiet(("127.0.0.1", PORT), handler)
    server.RequestHandlerClass.log_message = lambda *a, **k: None
    threading.Thread(target=server.serve_forever, daemon=True).start()
    return server


def main():
    sys.path.insert(0, str(HERE))
    import make_fixture_pdf

    statement = make_fixture_pdf.build(TMP / "statement-fixture.pdf")
    budget = TMP / "budget.xlsx"
    make_budget(budget, [["Market", 2000, 2000, 2000], ["Yakit", 1000, 1000, 1000],
                         ["Toplam", 3000, 3000, 3000]])

    server = serve()
    url = f"http://127.0.0.1:{PORT}/harcama-sifreli.html"
    try:
        with sync_playwright() as pw:
            browser = pw.chromium.launch(executable_path=CHROME)
            page = browser.new_page()
            errors = []
            page.on("pageerror", lambda e: errors.append(str(e)))
            page.on("dialog", lambda d: d.accept())
            page.goto(url)
            page.wait_for_selector("#lockBtn")

            print("\nfirst run — create the vault")
            check("fresh-vault prompt", page.inner_text("#lockTitle"), "Yeni kasa oluştur")
            page.fill("#pw", "1234")
            page.fill("#pw2", "9999")
            page.click("#lockBtn")
            check("mismatch rejected", page.inner_text("#lockErr"), "Şifreler eşleşmiyor.")
            page.fill("#pw2", "1234")
            page.click("#lockBtn")
            page.wait_for_selector("#app:not([hidden])", timeout=15000)
            check("app unlocked", page.is_visible("#app"), True)
            check("lock screen hidden after unlock", page.is_visible("#lock"), False)
            check("empty state", "Henüz veri yok" in page.inner_text("#tab-ozet"), True)
            check("pdf.js served from the repo, not a CDN",
                  page.evaluate("typeof pdfjsLib !== 'undefined'"), True)
            check("rules are the column layout", page.evaluate("RULES.layout"), "columns")

            print("\nstatement PDF import")
            page.click("button[data-tab=ekle]")
            page.set_input_files("#pdfInput", str(statement))
            page.wait_for_timeout(5000)
            log = page.inner_text("#log")
            check("reconciles against the statement's own period total",
                  "birebir uyuşuyor" in log, True)
            rows = {(t[0], t[1]): t[2:] for t in page.evaluate(
                "VAULT.transactions.map(t => [t.date, t.description, t.amount, t.category,"
                " t.installment_no, t.installment_total, t.original_amount, t.original_currency])")}
            check("transaction count", page.evaluate("VAULT.transactions.length"), 10)
            check("bonus-column row not counted as spend",
                  any("KAMPANYASI" in d for _, d in rows), False)
            check("credit is negative",
                  rows[("2025-12-16", "ÖDEMENİZ İÇİN TEŞEKKÜR EDERİZ")][0], -149340.29)
            check("instalment read", rows[("2025-12-12", "MOKAUNITED *ZARA GİYİM")][2:4], [1, 3])
            check("foreign original read", rows[("2026-01-21", "BARBOUR")][4:6], [438.0, "EUR"])
            check("undated fee row read", rows[("2026-01-09", "KKDF + BSMV")][0], 162.36)
            check("category assigned", rows[("2026-01-21", "BARBOUR")][1], "Giyim & Aksesuar")
            check("card mapped to its holder", page.evaluate(
                "Object.values(VAULT.cards).length === 1 && Object.values(VAULT.cards)[0] !== 'Diğer'"), True)
            check("owner bar hidden while there is only one card holder", page.is_visible("#ownerBar"), False)
            report = page.evaluate("buildReport(VAULT.transactions, VAULT.budget)")
            check("instalments due = open debit plans only", report["outstanding"], 1613.0 * 2)
            check("reversal plan shown as pending credit", report["pendingCredits"], -1760.0 * 2)
            check("schedule runs forward from the billing month",
                  sorted(report["schedule"]), ["2026-01", "2026-02"])
            check("largest open plan", report["largestPlans"][0]["merchant"], "MOKAUNITED ZARA GİYİM")

            cli_dir = TMP / "cli"
            subprocess.run([sys.executable, "expense_control.py", "parse", str(statement),
                            "--rules", "rules/garanti-bonus.json", "--out", str(cli_dir)],
                           cwd=str(ROOT / "tools/expense-control"), capture_output=True, text=True)
            cli = json.loads((cli_dir / "transactions.json").read_text(encoding="utf-8"))
            page_all = page.evaluate(
                "VAULT.transactions.map(t => [t.date, t.description, t.amount, t.category,"
                " t.installment_no, t.installment_total, t.original_amount])")
            check("page parser == CLI parser",
                  sorted(tuple(r) for r in page_all),
                  sorted((t["date"], t["description"], round(t["amount"], 2), t["category"],
                          t["installment_no"], t["installment_total"], t["original_amount"])
                         for t in cli))

            print("\ntransactions tab")
            page.click("button[data-tab=islemler]")
            check("rows listed", page.locator("#txnTable tbody tr").count(), 10)
            page.fill("#filterText", "airlines")
            check("same-day repeat kept as two charges",
                  page.locator("#txnTable tbody tr").count(), 2)
            page.fill("#filterText", "barbour")
            page.locator("#txnTable tbody tr:first-child select.catSel").select_option("Seyahat & Konak")
            page.wait_for_timeout(600)
            check("category reassignment persists", page.evaluate(
                "VAULT.transactions.find(t => t.description === 'BARBOUR').category"),
                "Seyahat & Konak")
            page.fill("#filterText", "")

            print("\nsorting and grouping")
            amounts = lambda: page.evaluate(
                "[...document.querySelectorAll('#txnTable tbody tr:not(.grp) td:nth-child(4)')].map(td => td.textContent)")
            check("default order is newest first",
                  page.evaluate("[...document.querySelectorAll('#txnTable tbody tr td:first-child')].map(td => td.textContent)")[:2],
                  ["21.01.2026", "09.01.2026"])
            page.click("#txnTable th[data-sort=amount]")
            check("amount header sorts largest first", amounts()[0], "23.022,30")
            page.click("#txnTable th[data-sort=amount]")
            check("second click flips the direction", amounts()[0], "-149.340,29")
            page.select_option("#groupBy", "category")
            groups = page.evaluate("[...document.querySelectorAll('#txnTable tbody tr.grp td')].map(td => td.textContent)")
            check("grouped by category with subtotals", any("Kategori: Giyim & Aksesuar" in g and "harcama" in g for g in groups), True)
            # BARBOUR was moved to Seyahat & Konak a few steps up, which makes it the largest group
            check("largest group first", "Kategori: Seyahat & Konak" in groups[0], True)
            check("group header carries the category glyph", groups[0].startswith("✈"), True)
            check("group count shown", "grup" in page.inner_text("#txnCount"), True)
            page.select_option("#groupBy", "month")
            months_seen = page.evaluate("[...document.querySelectorAll('#txnTable tbody tr.grp td')].map(td => td.textContent.split(' · ')[0])")
            check("grouped by month, newest first, Turkish names", months_seen, ["Ay: Ocak 2026", "Ay: Aralık 2025"])
            page.select_option("#groupBy", "")
            page.click("#txnTable th[data-sort=date]")

            print("\nspreadsheet budget import")
            page.click("button[data-tab=ekle]")
            page.set_input_files("#xlsxInput", str(budget))
            page.wait_for_timeout(2500)
            check("workbook table detected", "kalem" in page.inner_text("#xlsxPreview"), True)
            labels = page.evaluate("PENDING_BUDGET.table.rows.map(r => r.label)")
            check("category rows read", labels[:2], ["Market", "Yakit"])
            check("total row skipped", "Toplam" in labels, False)
            page.select_option("#bRow", label="Market")
            check("owner select offers both card holders",
                  set(page.evaluate("[...document.querySelectorAll('#bOwner option')].map(o => o.value)")) >= {"Ebru", "Namık"}, True)
            page.select_option("#bOwner", "Ebru")
            page.click("#bApply")
            page.wait_for_timeout(1500)
            check("single budget row applied to the chosen owner", page.evaluate("Object.keys(VAULT.budgets)"), ["Ebru"])
            check("months stored", page.evaluate("Object.keys(VAULT.budgets['Ebru']).length"), 3)
            check("value is absolute", page.evaluate("VAULT.budgets['Ebru']['2025-12']"), 2000)
            check("bare month names wrap into the next year",
                  sorted(page.evaluate("Object.keys(VAULT.budgets['Ebru'])")),
                  ["2025-12", "2026-01", "2026-02"])

            print("\nreport")
            page.click("button[data-tab=ozet]")
            page.wait_for_timeout(800)
            summary = page.inner_text("#tab-ozet").upper()
            check("monthly budget table rendered", "AY AY BÜTÇE" in summary, True)
            check("months carry Turkish names", "ARALIK 2025" in summary, True)
            check("status words are Turkish", "BÜTÇEDE" in summary or "AŞILDI" in summary or "SINIRDA" in summary, True)
            check("last-month tile leads the summary", page.inner_text("#tab-ozet .kpi:first-child span").upper().startswith("SON AY"), True)
            page.click("button[data-tab=taksit]")
            check("instalments tab shows the schedule", "AY AY TAAHHÜT" in page.inner_text("#tab-taksit").upper(), True)
            page.click("button[data-tab=ozet]")
            check("Toplam view adds the budget lines up under one badge", "TOPLAM" in summary, True)
            check("no spurious UNBUDGETED table", "BÜTÇE VS GERÇEKLEŞEN" in summary, False)

            print("\nowners")
            check("owner bar shown once a second person exists", page.is_visible("#ownerBar"), True)
            names = page.evaluate("[...document.querySelectorAll('#ownerBar button')].map(b => b.dataset.owner)")
            check("Toplam first, then each person", names[0] == "Toplam" and "Ebru" in names and len(names) == 3, True)
            check("Toplam pressed by default",
                  page.get_attribute("#ownerBar button[data-owner=Toplam]", "aria-pressed"), "true")
            page.click("#ownerBar button[data-owner=Ebru]")
            page.wait_for_timeout(500)
            check("Ebru has no card, so her view is empty", "Henüz veri yok" in page.inner_text("#tab-ozet"), True)
            holder = [n for n in names if n not in ("Toplam", "Ebru")][0]
            page.click(f"#ownerBar button[data-owner=\"{holder}\"]")
            page.wait_for_timeout(500)
            check("card holder's view carries the statement", page.evaluate("visible().length"), 10)
            check("holder without a budget line shows no budget table",
                  "AY AY BÜTÇE" in page.inner_text("#tab-ozet").upper(), False)
            page.click("#ownerBar button[data-owner=Toplam]")
            page.wait_for_timeout(500)
            check("Toplam adds every budget line up", page.evaluate("currentBudgetLine().months['2026-01']"), 2000)

            print("\ndrill-down")
            page.click("#tab-ozet tr.drill[data-cat='Giyim & Aksesuar']")
            page.wait_for_timeout(600)
            check("category row opens the transactions tab", page.is_visible("#tab-islemler"), True)
            check("category filter set", page.input_value("#filterCat"), "Giyim & Aksesuar")
            check("grouped by merchant for the detail view", page.input_value("#groupBy"), "merchant")
            check("only that category listed",
                  page.evaluate("[...new Set([...document.querySelectorAll('#txnTable tbody tr:not(.grp) select.catSel')].map(s => s.value))]"),
                  ["Giyim & Aksesuar"])
            check("person column filled", page.evaluate(
                "document.querySelector('#txnTable tbody tr:not(.grp) td:nth-child(6)').textContent"), holder)
            check("filter bar names the narrowing", "Giyim & Aksesuar" in page.inner_text("#filterBar"), True)
            page.click("#filterBar tr.grp, #txnTable tbody tr.grp >> nth=0")
            check("group header folds its rows", page.locator("#txnTable tbody tr[data-of='0'][hidden]").count() > 0, True)
            page.keyboard.press("Escape")
            page.wait_for_timeout(300)
            check("Escape returns to the summary", page.is_visible("#tab-ozet"), True)
            check("Escape clears the filter", page.input_value("#filterCat") + page.input_value("#groupBy"), "")

            print("\npersistence and secrecy")
            page.reload()
            page.wait_for_selector("#lockBtn")
            check("existing-vault prompt", page.inner_text("#lockTitle"), "Harcama Kontrolü")
            page.fill("#pw", "yanlis")
            page.click("#lockBtn")
            page.wait_for_timeout(2500)
            check("wrong password rejected", page.is_visible("#app"), False)
            page.fill("#pw", "1234")
            page.click("#lockBtn")
            page.wait_for_selector("#app:not([hidden])", timeout=15000)
            check("data survived reload", page.evaluate("VAULT.transactions.length"), 10)
            check("budget survived reload", page.evaluate("Object.keys(VAULT.budgets)"), ["Ebru"])
            check("vault schema is v2", page.evaluate("VAULT.version"), 2)
            raw = page.evaluate("localStorage.getItem('harcama-vault-v1')")
            for secret in ("BARBOUR", "MOKAUNITED", "5549", "TEŞEKKÜR"):
                check(f"'{secret}' not readable in storage", secret in raw, False)
            check("stored blob is an AES-GCM envelope",
                  sorted(json.loads(raw).keys()), ["ct", "iter", "iv", "salt", "v"])

            print("\nexport and password change")
            with page.expect_download() as dl:
                page.click("button[data-tab=islemler]")
                page.click("#exportCsv")
            csv_text = Path(dl.value.path()).read_text(encoding="utf-8")
            check("csv header", csv_text.splitlines()[0].startswith("﻿date,description"), True)
            check("csv rows", len(csv_text.strip().splitlines()) - 1, 10)
            page.click("button[data-tab=ayarlar]")
            page.fill("#npw", "abc")
            page.fill("#npw2", "abc")
            page.click("#changePw")
            page.wait_for_timeout(2500)
            page.reload()
            page.wait_for_selector("#lockBtn")
            page.fill("#pw", "1234")
            page.click("#lockBtn")
            page.wait_for_timeout(2500)
            check("old password no longer works", page.is_visible("#app"), False)
            page.fill("#pw", "abc")
            page.click("#lockBtn")
            page.wait_for_selector("#app:not([hidden])", timeout=15000)
            check("new password works", page.evaluate("VAULT.transactions.length"), 10)

            check("no uncaught js errors", errors, [])
            browser.close()
    finally:
        server.shutdown()
        shutil.rmtree(TMP, ignore_errors=True)

    print(f"\n{PASSED} passed, {FAILED} failed")
    return 1 if FAILED else 0


if __name__ == "__main__":
    sys.exit(main())
